apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api.yaml
  - gateway-lb.yaml
  - istio.yaml
  - digicert-externalaccount.yaml
  - digicert-clusterissuer-http01-gateway.yaml
  - digicert-clusterissuer-http01.yaml