apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digicert-clusterissuer-account-values
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: radix-keyvault
    kind: ClusterSecretStore
  target:
    name: digicert-clusterissuer-account-values
  dataFrom:
  - extract:
      key: digicert-external-account
