apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway-resource.yaml

patches:
  - target:
      kind: Service
      name: gateway-istio
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/externalTrafficPolicy
        value: Local