- op: replace
  path: /spec/ingress/0/from
  value:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitor
- op: replace
  path: /spec/ingress/1/from
  value:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitor
    