apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../components/third-party/gateway-api/v1.4.0

# patches:
# - path: version-patch.yaml
#   target:
#     kind: Kustomization
#     name: gateway-api
